services:
  chess-db:
    image: postgres:latest
    container_name: chess-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ChessBase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  kafka:
    image: confluentinc/cp-kafka:7.6.0 # ИСПРАВЛЕНО: стабильный образ, у которого нет проблем с appuser
    container_name: chess-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093' # ИСПРАВЛЕНО: внутреннее имя контейнера вместо localhost
      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # Открываем порты для Windows (9092) и для внутренней сети Docker (9094)
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,INTERNAL://kafka:9094'
      
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      
      # Настройки KRaft для Confluent образа
      CLUSTER_ID: '4L62xD9vTHmZydwN6H4kiA'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      - chess-db
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"] # ИСПРАВЛЕНО: универсальный хелсчек через netcat
      interval: 10s
      timeout: 5s
      retries: 6

  kafka-ui:
    image: tchiotludo/akhq:latest
    container_name: chess-kafka-ui
    ports:
      - "8080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka:
              properties:
                bootstrap.servers: "kafka:9094"
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  postgres_data:
  kafka_data:
